# Generated by Django 5.0.6 on 2025-12-02 06:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import hindu.models.event_category
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=200, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('image', models.TextField(blank=True, db_column='image', null=True)),
            ],
            options={
                'db_table': 'organization_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('alternativename', models.CharField(blank=True, db_column='alternativename', max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=2500, null=True)),
                ('type', models.CharField(choices=[('CONTINENT', 'CONTINENT')], db_column='type', default='CONTINENT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('hindu_population', models.CharField(db_column='hindu_population', max_length=100000)),
                ('overall_population', models.CharField(db_column='overall_population', max_length=100000)),
            ],
            options={
                'db_table': 'continent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('alternativename', models.CharField(blank=True, db_column='alternativename', max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=2500, null=True)),
                ('type', models.CharField(blank=True, choices=[('COUNTRY', 'COUNTRY')], db_column='type', default='COUNTRY', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_location', models.TextField(db_column='image_location')),
                ('hindu_population', models.CharField(db_column='hindu_population', max_length=100000)),
                ('overall_population', models.CharField(db_column='overall_population', max_length=100000)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('shortname', models.CharField(db_column='shortname', max_length=200)),
                ('headquarters', models.CharField(blank=True, db_column='headquarters', max_length=200, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('cityname', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('DISTRICT', 'DISTRICT'), ('CITY', 'CITY')], db_column='type', default='DISTRICT', max_length=30)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('est_by', models.CharField(max_length=200)),
                ('chairman', models.CharField(max_length=200)),
                ('est_date', models.CharField(max_length=50)),
                ('reg_id', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.TextField()),
                ('web_url', models.URLField()),
                ('org_detail', models.TextField()),
                ('mission', models.TextField()),
                ('org_images', models.TextField(blank=True, null=True)),
                ('org_logo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='PENDING', max_length=200)),
                ('geo_site', models.CharField(choices=[('MANDAL', 'M'), ('BLOCK', 'B'), ('VILLAGE', 'V'), ('DISTRICT', 'D'), ('STATE', 'S'), ('COUNTRY', 'C')], default='D', max_length=200)),
                ('organization_members', models.CharField(max_length=10000, null=True)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('shortname', models.CharField(db_column='shortname', max_length=200)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('STATE', 'STATE')], db_column='type', default='STATE', max_length=30)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('desc', models.CharField(db_column='desc', max_length=10000)),
                ('image', models.TextField(blank=True, db_column='image', null=True)),
            ],
            options={
                'db_table': 'organization_sub_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], db_column='training_type', default='offline', max_length=10)),
                ('certificate', models.TextField(blank=True, db_column='certificate', null=True)),
                ('user_type', models.CharField(choices=[('MEMBER', 'MEMBER'), ('ADMIN', 'ADMIN')], db_column='user_type', default='MEMBER', max_length=45)),
            ],
            options={
                'db_table': 'trainer_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=10000, null=True)),
                ('image', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'training_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingSubCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('desc', models.CharField(db_column='desc', max_length=10000)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=hindu.models.event_category.unique_id_gen_evnt_catg, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pic', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Event_category',
            },
        ),
        migrations.CreateModel(
            name='EventCategory1',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pic', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(db_column='id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, db_column='full_name', max_length=200, null=True)),
                ('father_name', models.CharField(blank=True, db_column='father_name', max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, db_column='contact_number', max_length=10, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=50)),
                ('profile_pic', models.TextField(blank=True, db_column='profile_pic', null=True)),
                ('is_member', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=50)),
                ('verification_otp', models.CharField(blank=True, db_column='verification_otp', max_length=6, null=True)),
                ('verification_otp_created_time', models.DateTimeField(db_column='verification_otp_created_time', null=True)),
                ('verification_otp_resend_count', models.IntegerField(db_column='verification_otp_resend_count', default=0)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='status', default='CREATED', max_length=50)),
                ('training_type', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], db_column='training_type', default='offline', max_length=10)),
                ('certificate', models.TextField(blank=True, db_column='certificate', null=True)),
                ('user_type', models.CharField(choices=[('MEMBER', 'MEMBER'), ('ADMIN', 'ADMIN')], db_column='user_type', default='MEMBER', max_length=45)),
                ('account_type', models.CharField(max_length=100)),
                ('family_images', models.JSONField(blank=True, default=list)),
                ('surname', models.CharField(blank=True, db_column='surname', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('municipality', models.CharField(blank=True, db_column='municipality', max_length=45, null=True)),
                ('population', models.CharField(blank=True, db_column='population', max_length=45, null=True)),
                ('desc', models.CharField(db_column='desc', max_length=2500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('BLOCK', 'BLOCK'), ('TOWN', 'TOWN')], db_column='type', default='BLOCK', max_length=30)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hindu.district')),
            ],
            options={
                'db_table': 'block',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date')),
                ('start_time', models.TimeField(blank=True, db_column='start_time', null=True)),
                ('end_time', models.TimeField(blank=True, db_column='end_time', null=True)),
                ('tag', models.CharField(blank=True, choices=[('TEMPLE', 'TEMPLE'), ('GOSHALA', 'GOSHALA')], db_column='tag', default=None, max_length=200, null=True)),
                ('tag_id', models.CharField(max_length=200, null=True)),
                ('tag_type_id', models.CharField(blank=True, max_length=200, null=True)),
                ('geo_site', models.CharField(choices=[('MANDAL', 'M'), ('BLOCK', 'B'), ('VILLAGE', 'V'), ('DISTRICT', 'D'), ('STATE', 'S'), ('COUNTRY', 'C')], default='V', max_length=200)),
                ('map_location', models.CharField(blank=True, db_column='map_location', max_length=200, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=200, null=True)),
                ('contact_name', models.CharField(blank=True, db_column='contact_name', max_length=45, null=True)),
                ('contact_phone', models.CharField(blank=True, db_column='contact_phone', max_length=10, null=True)),
                ('contact_email', models.EmailField(blank=True, db_column='contact_email', max_length=200, null=True)),
                ('desc', models.TextField(blank=True, db_column='desc', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='status', default='INACTIVE', max_length=200)),
                ('image_location', models.JSONField(blank=True, db_column='image_location', default=list, null=True)),
                ('event_status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('ONGOING', 'ongoing')], db_column='event_status', default='UPCOMING', max_length=200)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hindu.eventcategory')),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('_id', models.UUIDField(db_column='_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(db_column='body', max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_time_ago', models.CharField(blank=True, db_column='posted_time_ago', max_length=255)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, db_column='event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hindu.event')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('desc', models.CharField(db_column='desc', max_length=1000000)),
                ('image', models.TextField(blank=True, null=True)),
                ('location', models.CharField(db_column='location', max_length=200)),
                ('start_date', models.DateTimeField(blank=True, db_column='start_date', max_length=20, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='end_date', max_length=20, null=True)),
                ('trainer_name', models.CharField(db_column='trainer_name', max_length=200)),
                ('contact_details', models.CharField(db_column='contact_details', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], db_column='status', default='PENDING', max_length=50)),
                ('video', models.TextField(blank=True, db_column='video', null=True)),
                ('training_type', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], db_column='training_type', default='offline', max_length=100)),
                ('geo_site', models.CharField(choices=[('MANDAL', 'M'), ('BLOCK', 'B'), ('VILLAGE', 'V'), ('DISTRICT', 'D'), ('STATE', 'S'), ('COUNTRY', 'C')], default='D', max_length=50)),
                ('training_link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='hindu.trainingcategory')),
                ('object_id', models.ForeignKey(blank=True, db_column='object_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Training', to='hindu.district')),
                ('sub_category', models.ForeignKey(blank=True, db_column='sub_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='hindu.trainingsubcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Training', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('desc', models.CharField(blank=True, db_column='desc', default=None, max_length=5000, null=True)),
                ('mapUrl', models.URLField(blank=True, db_column='map_url', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='status', default='INACTIVE', max_length=50)),
                ('pin_code', models.CharField(db_column='pin_code', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_location', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('VILLAGE', 'VILLAGE'), ('AREA', 'AREA')], db_column='type', default='VILLAGE', max_length=30)),
                ('old_village_code', models.CharField(db_column='old_village_code', max_length=45, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='hindu.block')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'village',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='hindu.village'),
        ),
    ]
